openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  contact:
    name: Support
    email: srcgithub@gmail.com
    url: 'https://openweathermap.org/api'
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
  description: "Get the current weather, daily forecasts for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and \"this day in history\" charts are available for your reference. Interactive maps show precipitation, clouds, pressure, and wind around your location's stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the 'current' endpoint only from the OpenWatherMap API. <br/><br/> **Note**: all parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the 'id' parameter) will provide the most precise location results."
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: weather
      tags:
        - Weather endpoints
      responses: {}
      operationId: get-weather
      description: |-
        Access current weather data for any location including over 200,000 cities. Current weather is frequently updated based on global models and data from more than 40,000 weather stations
        Data is available in JSON, XML, or HTML format. Available for both Free and paid subscriptions
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**. Search by zip code. *Example 95050*'
        - schema:
            type: string
          in: query
          name: units
          description: "*Example: imperial*. Possible values: 'standard'"
        - schema:
            type: string
          in: query
          name: id
          description: "**City ID**. *Example: '2172797'"
        - schema:
            type: string
          in: query
          name: lat
          description: '**Latitude**. *Example: 35*'
        - schema:
            type: string
          in: query
          name: lon
          description: |
            **Longitude**. *Example: 139*.
        - schema:
            type: string
          in: query
          name: lang
          description: '**Language**. *Example: en* You can use language parameters to select how the information will be presented.'
        - schema:
            type: string
          in: query
          name: mode
          description: '**Mode**. *Example: html* Determines the format of the request.'
        - schema:
            type: string
          in: query
          name: q
          description: '*Example: London*. You can call by city name.'
    parameters: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
